<a href="https://colab.research.google.com/github/TheDerik/Data-Science-intern-at-Celebal-Technologies/blob/main/Week_4_COE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Apply Bayes Theorem**

In [1]:
P_D = 0.01
P_not_D = 1 - P_D
P_T_given_D = 0.95
P_T_given_not_D = 0.05
P_T = (P_T_given_D * P_D) + (P_T_given_not_D * P_not_D)
P_D_given_T = (P_T_given_D * P_D) / P_T

print(f"Probability of having the disease given a positive test result: {P_D_given_T:.4f}")

Probability of having the disease given a positive test result: 0.1610


In [2]:
import numpy as np

# 3x3 matrix
A = np.array([[4, -2, 1],
              [1, 1, 2],
              [1, -2, 0]])

# Calculating eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:")
print(eigenvalues)

print("Eigenvectors:")
print(eigenvectors)


Eigenvalues:
[3.+0.j         1.+1.41421356j 1.-1.41421356j]
Eigenvectors:
[[-8.94427191e-01+0.j          5.02955691e-01+0.08891084j
   5.02955691e-01-0.08891084j]
 [-4.47213595e-01+0.j          6.91564075e-01+0.j
   6.91564075e-01-0.j        ]
 [-2.84021877e-16+0.j         -2.51477845e-01+0.44455422j
  -2.51477845e-01-0.44455422j]]


In [4]:
# Calculating the Determinant of a 3x3 Matrix and Find Its Inverse if Possible
B = np.array([[2, -1, 0],
              [1, 3, -2],
              [0, -1, 1]])

det_B = np.linalg.det(B)

print(f"Determinant of B: {det_B:.4f}")

if det_B != 0:
    # Calculate inverse
    inv_B = np.linalg.inv(B)
    print("Inverse of B:")
    print(inv_B)
else:
    print("Matrix B is not invertible.")

Determinant of B: 3.0000
Inverse of B:
[[ 0.33333333  0.33333333  0.66666667]
 [-0.33333333  0.66666667  1.33333333]
 [-0.33333333  0.66666667  2.33333333]]


In [5]:
import scipy.stats as stats

# Mean and standard deviation
mu = 0
sigma = 1

# Defining the Normal distribution
normal_dist = stats.norm(mu, sigma)

# Calculating probability of a value less than or equal to a certain point
x = 1.96
probability = normal_dist.cdf(x)

print(f"Probability of a value less than or equal to {x}: {probability:.4f}")

# Calculating the probability within a range
x1, x2 = -1.96, 1.96
probability_range = normal_dist.cdf(x2) - normal_dist.cdf(x1)

print(f"Probability of a value between {x1} and {x2}: {probability_range:.4f}")


Probability of a value less than or equal to 1.96: 0.9750
Probability of a value between -1.96 and 1.96: 0.9500
